wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1649163791
    t:
      1:
      - 1
      - 41
      2:
      - 1
      - 41
      3:
      - 2
      4: 3.9.7
      5: 0.12.11
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.001
